#!/usr/bin/env python3
"""Build the Trainer HQ page into a module the API function serves.

    python3 tools/build-hq.py

Unlike every other page on this site, Trainer HQ must NOT end up as an HTML
file in the repo root: Vercel would serve it statically at /trainer-hq and the
pay rates, promo codes and bonus-scheme numbers on it would be public. So it is
compiled into api/_page.js instead — a file inside api/ whose name starts
with an underscore, which Vercel treats as a shared module rather than an
endpoint and never serves. api/hq/page.js requires it and hands it out only to
a request carrying a valid session.

Source lives in src/:
    page.html      the page body, with front matter and <!--#include name-->
    partials/*.html

"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
PARTIALS = SRC / "partials"
OUT = ROOT / "api" / "_page.js"

FRONT_MATTER = re.compile(r"\A\s*<!--(.*?)-->", re.S)
INCLUDE = re.compile(r"<!--#include\s+([a-z0-9_-]+)\s*-->")


def front_matter(text: str) -> tuple[dict[str, str], str]:
    match = FRONT_MATTER.match(text)
    if not match:
        raise SystemExit("src/hq/page.html is missing its front-matter comment")
    meta = {}
    for line in match.group(1).strip().splitlines():
        line = line.strip()
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
    return meta, text[match.end():].lstrip("\n")


def expand(text: str, partials: dict[str, str], depth: int = 0) -> str:
    if depth > 5:
        raise SystemExit("include nesting too deep — check for a cycle")

    def sub(match: re.Match[str]) -> str:
        name = match.group(1)
        if name not in partials:
            raise SystemExit(f"unknown partial: {name}")
        return expand(partials[name], partials, depth + 1)

    return INCLUDE.sub(sub, text)


def asset_version(*paths: Path) -> str:
    """Short content hash, so a CSS change reaches browsers.

    vercel.json caches /css and /js for a year as immutable, which is right for
    content-addressed URLs and wrong for stable ones — without this, an edit to
    trainer-hq.css would never reach a trainer who had already loaded it."""
    digest = hashlib.sha256()
    for path in paths:
        digest.update(path.read_bytes())
    return digest.hexdigest()[:10]


def literal(text: str) -> str:
    """Quote HTML for a JavaScript template literal."""
    return (
        text.replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )


def main() -> int:
    if not SRC.is_dir():
        raise SystemExit(f"missing {SRC}")

    partials = {p.stem: p.read_text() for p in PARTIALS.glob("*.html")}
    meta, body = front_matter((SRC / "page.html").read_text())
    page = expand(body, partials)

    version = asset_version(ROOT / "css" / "portal.css", ROOT / "js" / "portal.js")
    for key, value in {
        "{{title}}": meta.get("title", "Trainer HQ"),
        "{{description}}": meta.get("description", ""),
        "{{v}}": version,
    }.items():
        page = page.replace(key, value)

    left = re.findall(r"\{\{([a-z_]+)\}\}", page)
    if left:
        raise SystemExit(f"unfilled placeholder(s) in page.html: {sorted(set(left))}")

    OUT.write_text(
        "'use strict';\n"
        "/* GENERATED by tools/build.py — edit src/, not this file. */\n\n"
        f"const PAGE = `{literal(page)}`;\n\n"
        "function render() {\n"
        "  return PAGE;\n"
        "}\n\n"
        "module.exports = { render, version: " + repr(version).replace("'", '"') + " };\n"
    )

    print(f"  api/_page.js{'':<21}{OUT.stat().st_size / 1024:6.1f} KB   assets v{version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
