'use strict';
/* GENERATED by tools/build.py — edit src/, not this file. */

const PAGE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Trainer HQ — Oak Cliff Pilates</title>
<meta name="robots" content="noindex, nofollow, noarchive">
<meta name="referrer" content="same-origin">
<meta name="theme-color" content="#0B0B0B">
<link rel="icon" href="/favicon.png" type="image/png">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Khand:wght@400;500;600;700&family=Montserrat:wght@300;400;600;700;900&display=swap">
<link rel="stylesheet" href="/css/tokens.css">
<link rel="stylesheet" href="/css/base.css?v=0279ef74aa">
<link rel="stylesheet" href="/css/portal.css?v=0279ef74aa">
</head>

<body class="hq">
<a class="skip" href="#hq-main">Skip to content</a>
<header class="hq-top">
  <div class="hq-top__in">
    <a class="hq-top__mark" href="#today">
      <img class="logo-puck" src="/img/logo-puck.png" alt="" width="36" height="36">
      <b>Trainer HQ</b>
    </a>
    <span class="hq-top__tag">Internal — trainers only</span>
  </div>
</header>


<div class="hq-shell">

  <nav class="hq-nav" aria-label="Trainer HQ sections">
    <div class="hq-nav__label">Trainer HQ</div>
    <ol>
      <li><a href="#today"><span>01</span>Today</a></li>
      <li><a href="#announcements"><span>02</span>Announcements</a></li>
      <li><a href="#events"><span>03</span>Events</a></li>
      <li><a href="#offers"><span>04</span>Offers</a></li>
      <li><a href="#goal"><span>05</span>The 1,000</a></li>
      <li><a href="#classes"><span>06</span>Classes</a></li>
      <li><a href="#studio"><span>07</span>Studio</a></li>
      <li><a href="#onboarding"><span>08</span>Onboarding</a></li>
      <li><a href="#resources"><span>09</span>Resources</a></li>
    </ol>
  </nav>

  <main class="hq-main" id="hq-main">

  <!-- ══ 01 TODAY ═══════════════════════════════════════════════════ -->
  <section class="hq-hero" id="today">
    <div class="hq-eyebrow">Oak Cliff Pilates — internal</div>
    <h1>Trainer<br><span>HQ</span></h1>
    <p class="hq-hero__lede">Everything you need before you step on the floor. The class
      standard, what is on the calendar, and what we are pushing right now.</p>
    <div class="hq-quick">
      <a href="https://app.arketa.co" target="_blank" rel="noopener">Open Arketa</a>
      <a href="#studio-issue">Report a studio issue</a>
      <a href="#offers">Current offers</a>
      <a href="https://docs.google.com/document/d/1qxPZ9cg-ST7CLNCK0TYsXTntPhKJD_P5Ir9E-gJal04/edit" target="_blank" rel="noopener">Handbook</a>
    </div>
  </section>

  <!-- ══ 02 ANNOUNCEMENTS ═══════════════════════════════════════════ -->
  <section class="hq-sec" id="announcements">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">02 — From the office</div>
      <h2 class="hq-h2">Announcements</h2>
      <p>Straight from the office. Check before every shift.</p>
      <p class="hq-live" id="hq-announcements-status"><span class="hq-live__dot"></span><span>Loading…</span></p>
    </div>
    <div class="hq-card hq-card--plain" id="hq-announcements">
      <div class="hq-skeleton"><div></div><div></div><div></div></div>
    </div>
    <p class="hq-note" style="margin-top:12px">Something everyone needs to know? Add a row to
      the <b>ANNOUNCEMENTS</b> tab in the events workbook and it shows up here.</p>
  </section>

  <!-- ══ 03 EVENTS ══════════════════════════════════════════════════ -->
  <section class="hq-sec" id="events">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">03 — On the calendar</div>
      <h2 class="hq-h2">Events</h2>
      <p>Straight from the events workbook — name, date, location, who is teaching and
        what it pays. Events are how this brand grows. If you are teaching one, you are
        running it. If you are not, come anyway.</p>
      <p class="hq-live" id="hq-events-status"><span class="hq-live__dot"></span><span>Loading…</span></p>
    </div>

    <div class="hq-events" id="hq-events">
      <div class="hq-card hq-card--plain"><div class="hq-skeleton"><div></div><div></div><div></div></div></div>
    </div>

    <div class="hq-grid hq-grid--2" style="margin-top:22px">
      <div class="hq-card">
        <div class="hq-eyebrow">If you are teaching</div>
        <h3 class="hq-h3" style="margin:10px 0 0">You are not just the instructor — you are the host</h3>
        <ul class="hq-list">
          <li><strong>Pay</strong> is on your regular check. The rate for each event is on
            its card above, taken from the event tab in the workbook. Confirm with Amanda
            before the date.</li>
          <li><strong>Promote it.</strong> Repost the flyer to your story, tag
            <strong>@oakcliffpilates</strong>, and personally invite your regulars.</li>
          <li><strong>Arrive at the call time</strong> on the card. Help set up — do not
            just show up to cue.</li>
          <li><strong>Bring the pitch.</strong> Know the current offers cold. Every
            attendee is a lead.</li>
          <li><strong>Stay after.</strong> Talk to people. Get names. Answer membership
            questions.</li>
        </ul>
      </div>
      <div class="hq-card">
        <div class="hq-eyebrow">If you are not teaching</div>
        <h3 class="hq-h3" style="margin:10px 0 0">Come anyway</h3>
        <p class="hq-note" style="margin-top:12px">Trainers in the room is the whole reason
          our events do not feel like fitness marketing. Take the class. Bring a friend. Be
          in the photos.</p>
        <ul class="hq-list">
          <li>Events are free for trainers unless the card says otherwise.</li>
          <li>Repost the flyer even when it is not your class.</li>
          <li>Your clients follow you, not us — one story from you moves more tickets
            than a paid ad.</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- ══ 04 OFFERS ══════════════════════════════════════════════════ -->
  <section class="hq-sec" id="offers">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">04 — What to push</div>
      <h2 class="hq-h2">Offers running now</h2>
      <p>Know these by heart. When a client asks “what should I do next?” you should have
        an answer in one sentence — and the link ready. Every price here is the one the
        checkout actually charges.</p>
    </div>

    <div class="hq-grid hq-grid--2">
      <article class="hq-offer">
        <div class="hq-offer__code">Intro offer</div>
        <div class="hq-offer__body">
          <div class="hq-offer__who">New clients · any studio</div>
          <h3 class="hq-h3">1 week unlimited</h3>
          <div class="hq-offer__price">$59</div>
          <p>A full week of unlimited classes, at any of the three studios. First-time
            clients only. A single charge — one week, not a rolling subscription.</p>
          <div class="hq-say">
            <b>Say it like this</b>
            <q>$59 for a full week unlimited — come every day and see what sticks.</q>
          </div>
          <p style="margin-top:14px"><a href="https://oakcliffpilates.com/pricing/intro-1-week" target="_blank" rel="noopener">oakcliffpilates.com/pricing/intro-1-week</a></p>
        </div>
      </article>

      <article class="hq-offer">
        <div class="hq-offer__code">Intro offer</div>
        <div class="hq-offer__body">
          <div class="hq-offer__who">New clients · Lower Greenville only</div>
          <h3 class="hq-h3">2 weeks unlimited</h3>
          <div class="hq-offer__price">$89</div>
          <p>Two weeks of unlimited classes at Lower Greenville. The fullest way to try
            us. <strong>Do not promise it at Uptown or Bishop Arts</strong> — it is not
            valid there.</p>
          <div class="hq-say">
            <b>Say it like this</b>
            <q>$89 for two weeks unlimited at Lower Greenville — come every day if you want to.</q>
          </div>
          <p style="margin-top:14px"><a href="https://oakcliffpilates.com/pricing/2-week-unlimited" target="_blank" rel="noopener">oakcliffpilates.com/pricing/2-week-unlimited</a></p>
        </div>
      </article>
    </div>

    <div class="hq-card" style="margin-top:14px">
      <div class="hq-eyebrow">Where to send them</div>
      <h3 class="hq-h3" style="margin:10px 0 10px">Both intro offers live in one place</h3>
      <p><a href="https://oakcliffpilates.com/pricing/intro-offers" target="_blank" rel="noopener">oakcliffpilates.com/pricing/intro-offers</a>
        — save it in your notes app and text it straight from the floor.</p>
    </div>

    <div class="hq-grid hq-grid--2" style="margin-top:14px">
      <div class="hq-card">
        <div class="hq-eyebrow">When the intro runs out</div>
        <h3 class="hq-h3" style="margin:10px 0 0">The memberships, cheapest first</h3>
        <p class="hq-note" style="margin-top:12px">All month to month. No contract, cancel
          any time, and they can pause for up to 3 months with 10 days&rsquo; notice.</p>
        <ul class="hq-list">
          <li><strong>OCP Lite — $99:</strong> 4 classes a month, about $25 a class.</li>
          <li><strong>Afternoon Unlimited — $119:</strong> every weekday class between
            10am and 4pm, all three studios.</li>
          <li><strong>Perfect Balance — $159:</strong> 8 classes a month, about $20 a class.</li>
          <li><strong>Studio Unlimited — $159:</strong> unlimited at one studio, whichever
            is theirs.</li>
          <li><strong>The Regular — $189:</strong> 12 classes a month, under $16 a class.</li>
          <li><strong>Unlimited — $209:</strong> every class, every studio, plus the perks.
            The most popular one.</li>
        </ul>
      </div>

      <div class="hq-card">
        <div class="hq-eyebrow">Yours to give</div>
        <h3 class="hq-h3" style="margin:10px 0 0">Trainer code — 3 months unlimited, 20% off</h3>
        <p class="hq-note" style="margin-top:12px">Only for special clients who are on the
          fence. It is not a public offer and it does not go on social.</p>
        <ul class="hq-list">
          <li>Your code is <strong>YOURNAME20</strong> — Charley&rsquo;s is <strong>CHARLEY20</strong>.</li>
          <li>One-on-one only: text it, say it, hand it over in person.</li>
        </ul>
      </div>
    </div>

    <div class="hq-card" style="margin-top:14px">
      <div class="hq-eyebrow">How to hand it off</div>
      <h3 class="hq-h3" style="margin:10px 0 10px">Do not sell. Point.</h3>
      <p>Your job is not to close — it is to name the right next step and get them to the
        front desk or the link. If someone is on the fence, get their name to the front desk
        and they will follow up within 12 hours. <strong>Never invent a discount that is not
        on this page.</strong></p>
    </div>

    <div class="hq-card hq-card--plain" style="margin-top:14px">
      <div class="hq-eyebrow">Other promo codes and specials</div>
      <p class="hq-note" style="margin-top:10px">Anything seasonal or partner-specific goes
        here so there is one list. <span class="hq-tk">Needs content</span></p>
    </div>
  </section>

  <!-- ══ 05 THE 1,000 ═══════════════════════════════════════════════ -->
  <section class="hq-sec" id="goal">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">05 — The number</div>
      <h2 class="hq-h2">1,000 active members</h2>
      <p>That is the goal, and we want it before the end of the year. Every intro offer you
        hand out and every event you post moves this number.</p>
    </div>

    <div class="hq-card hq-goal">
      <div class="hq-eyebrow">Where we stand</div>
      <p class="hq-note" id="hq-goal-updated" style="margin-top:8px">Counted from the events workbook</p>
      <div class="hq-nums" id="hq-goal-nums">
        <div class="hq-num hq-num--now"><b>—</b><span>Active members today</span></div>
        <div class="hq-num"><b>—</b><span>Left to hit the goal</span></div>
        <div class="hq-num"><b>1,000</b><span>The goal</span></div>
      </div>
      <div class="hq-rail">
        <div class="hq-rail__track"><div class="hq-rail__fill" id="hq-rail-fill"></div></div>
        <div class="hq-rail__legend" id="hq-rail-legend"><span>Loading…</span><span></span></div>
      </div>
    </div>

    <div class="hq-grid hq-grid--2" style="margin-top:14px">
      <div class="hq-card">
        <div class="hq-eyebrow">What moves it</div>
        <h3 class="hq-h3" style="margin:10px 0 0">It is a handful a week</h3>
        <ul class="hq-list">
          <li>Hand the $59 week to every first-timer in your class — by name, before they
            leave.</li>
          <li>Follow up when someone&rsquo;s intro week ends. That conversation is where
            memberships come from.</li>
          <li>Post the events. Event attendees are the warmest leads we get.</li>
          <li>Save your <strong>YOURNAME20</strong> code for the people who are genuinely
            on the fence.</li>
        </ul>
      </div>
      <div class="hq-card">
        <div class="hq-eyebrow">Keep it honest</div>
        <h3 class="hq-h3" style="margin:10px 0 0">Active means active</h3>
        <p class="hq-note" style="margin-top:12px">A member who stops coming is a member we
          lose in 60 days. Retention counts as much as sign-ups toward the 1,000.</p>
        <ul class="hq-list">
          <li>Learn names. Use them in class.</li>
          <li>Notice when a regular disappears — tell the front desk.</li>
          <li>Bring-a-friend works: ask people to bring someone.</li>
        </ul>
      </div>
    </div>
  </section>

  <!-- ══ 06 CLASSES ═════════════════════════════════════════════════ -->
  <section class="hq-sec" id="classes">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">06 — Classes &amp; client experience</div>
      <h2 class="hq-h2">The class standard</h2>
      <p>What each class type is, how every class runs, and the two desk policies that
        come up most.</p>
    </div>

    <h3 class="hq-h4">Class types</h3>
    <p class="hq-note" style="margin:8px 0 14px">Clients book by class type. The schedule is
      a promise — teach what it says, every time, at every location, from every trainer.</p>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ct-1">
        <span class="hq-acc__sign"></span>Classical AF<span class="hq-level">All levels</span>
      </button>
      <div class="hq-acc__panel" id="ct-1" hidden>
        <p>Classical AF stays rooted in traditional Pilates movement vocabulary, principles,
          pacing and flow, even though you are not expected to follow the classical order.
          Programming should feel recognisable and familiar to someone with a classical
          background, with contemporary variations used selectively rather than driving the
          class.</p>
        <p>It should be appropriately challenging for experienced clients while remaining
          accessible to all levels through modifications and regressions. Emphasise control,
          precision, full-body integration and efficient transitions — not athletic
          conditioning or elaborate choreography.</p>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ct-2">
        <span class="hq-acc__sign"></span>OG Reformer<span class="hq-level">All levels</span>
      </button>
      <div class="hq-acc__panel" id="ct-2" hidden>
        <p>Our contemporary, athletic Reformer class, and the one with the greatest range for
          creative programming. Classes may incorporate classical movement but should
          primarily reflect modern Pilates through varied sequencing, unilateral work,
          strength and endurance challenges, and more athletic movement patterns.</p>
        <p>Pacing can be quicker and progressions more dynamic than Classical AF, while the
          base programming stays accessible to all levels. Creativity is encouraged, but
          movement should remain purposeful, Pilates-informed, and centred on effective use
          of the Reformer rather than complexity for its own sake.</p>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ct-3">
        <span class="hq-acc__sign"></span>Jumpboard<span class="hq-level">All levels</span>
      </button>
      <div class="hq-acc__panel" id="ct-3" hidden>
        <p>A full-body, all-level Reformer class built around multiple jumping series using
          the Jumpboard or Cardio Tramp, depending on studio equipment. Each class should
          feature several distinct jump sequences — supine, side-lying, quadruped or other
          appropriate orientations — rather than treating jumping as a brief add-on.</p>
        <p>Use classical and contemporary Reformer movement between jump series to create
          balance, muscular variety and recovery while keeping a cohesive full-body workout.
          It should feel athletic and dynamic, but stay controlled, Pilates-informed and
          accessible through spring changes, range adjustments, tempo modifications and
          lower-impact options.</p>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ct-4">
        <span class="hq-acc__sign"></span>Restorative Reformer<span class="hq-level">All levels</span>
      </button>
      <div class="hq-acc__panel" id="ct-4" hidden>
        <p>A full-body, all-level class centred on stretching, mobility, flexibility and
          gentle movement, using the Reformer as the primary apparatus. It should feel
          engaging and purposeful without the physical demand of a traditional workout class,
          emphasising breath, grounding, control and ease of movement.</p>
        <p>Slower transitions, supported positions and sustained stretches all work, but the
          class stays distinctly Reformer-based rather than becoming a mat, yoga or
          meditation class. Calm, accessible and physically restorative — without becoming
          overtly spiritual, philosophical or passive.</p>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ct-5">
        <span class="hq-acc__sign"></span>Arms, Ass &amp; Abs<span class="hq-level">Intermediate</span>
      </button>
      <div class="hq-acc__panel" id="ct-5" hidden>
        <p>Our intermediate-advanced contemporary format. It should feel distinctly more
          demanding than OG Reformer. Programming may assume greater body awareness,
          strength, endurance, coordination and familiarity with the Reformer, so you can
          begin at a higher baseline and progress movements further.</p>
        <p>Incorporate stronger resistance, sustained muscular work, more challenging
          stability and balance demands, advanced progressions and efficient transitions
          while maintaining good movement quality. Modifications should always be available
          when needed, but <strong>do not reduce the class to an all-level experience
          because a less-experienced client is present.</strong></p>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ct-6">
        <span class="hq-acc__sign"></span>Tabata Pilates<span class="hq-level">Intermediate</span>
      </button>
      <div class="hq-acc__panel" id="ct-6" hidden>
        <p>An intermediate-level, full-body class combining contemporary OG-style Reformer
          programming with short bursts of higher-intensity Tabata movement.</p>
        <p>Include multiple Tabata segments of roughly three minutes between Reformer
          sequences — about 9–10 minutes of the class in total — with around 35 minutes of
          Reformer work including the warm-up and cool-down. The Tabata portions should
          meaningfully elevate heart rate and create a cardiovascular challenge; the Reformer
          segments stay athletic, purposeful and distinctly Pilates-based. It should feel
          energetic and cohesive rather than like two separate workouts.</p>
      </div>
    </div>

    <h3 class="hq-h4" style="margin-top:36px">Run of show</h3>
    <p class="hq-note" style="margin:8px 0 0">Every class is 45 minutes, start to finish.</p>

    <div class="hq-flow" style="margin-top:18px">
      <div class="hq-step">
        <div class="hq-step__when">−15 min<small>Pre-class</small></div>
        <div>
          <h4 class="hq-h3">Be ready before clients enter</h4>
          <ul class="hq-list">
            <li><strong>Set the studio.</strong> Music on, lighting adjusted, and any needed
              props or equipment prepared before clients begin arriving.</li>
            <li><strong>Review the roster in advance.</strong> Know who is attending and
              identify first-time clients before class begins.</li>
            <li><strong>Greet every client.</strong> By name wherever possible, whether it is
              their first class or their 200th.</li>
            <li><strong>Orient new clients before class.</strong> Familiarise first-timers
              with the Reformer, the studio setup, and any essential equipment or safety
              expectations.</li>
            <li><strong>Address limitations individually.</strong> Check in privately about
              injuries, restrictions or movement limitations — not by asking the room
              collectively at the start of class.</li>
          </ul>
        </div>
      </div>

      <div class="hq-step">
        <div class="hq-step__when">0:00 — 45:00<small>During class</small></div>
        <div>
          <h4 class="hq-h3">Teach the class that is on the schedule</h4>
          <ul class="hq-list">
            <li><strong>Keep the Reformer central.</strong> Mat work may be incorporated
              selectively, but stays a light feature rather than a substantial portion of
              class.</li>
            <li><strong>Prioritise flow and efficient transitions.</strong> Thoughtful
              sequencing, spring changes, prop use and transitions that keep class moving
              smoothly and intentionally.</li>
            <li><strong>Progress challenge appropriately.</strong> Build difficulty logically
              and give clients room to progress, without making complexity or intensity the
              starting point unnecessarily.</li>
            <li><strong>Keep warm-up and cool-down concise</strong> — roughly six minutes
              combined, leaving the majority of class for substantive programming.</li>
            <li><strong>Modify appropriately</strong>, within reason, balancing the needs and
              experience of the full group.</li>
            <li><strong>Challenge clients while reading the room.</strong> Encourage effort
              and intention while staying aware of individual needs and the overall group
              experience.</li>
            <li><strong>Motivate without overstepping.</strong> Encouragement, energy and
              positive reinforcement are welcome. Avoid life coaching and overtly spiritual,
              philosophical or belief-based instruction.</li>
          </ul>
        </div>
      </div>

      <div class="hq-step">
        <div class="hq-step__when">45:00<small>Closing &amp; after</small></div>
        <div>
          <h4 class="hq-h3">Do not skip the last two minutes</h4>
          <ul class="hq-list">
            <li><strong>Thank the class</strong> out loud, before anyone begins leaving the
              room.</li>
            <li><strong>Encourage client feedback.</strong> When appropriate, remind clients
              how to share feedback and leave positive reviews.</li>
            <li><strong>Remain available for questions.</strong> Stay on the studio floor for
              several minutes after class. Do not immediately disappear into the back or
              leave the studio.</li>
            <li><strong>Discuss next steps with eligible clients.</strong> First-timers and
              anyone on an introductory offer should be asked what comes next. Know the
              current offers well enough to speak about them confidently and accurately.</li>
          </ul>
        </div>
      </div>
    </div>

    <div class="hq-grid hq-grid--2" style="margin-top:28px">
      <div class="hq-card">
        <div class="hq-eyebrow">Parking validations</div>
        <h3 class="hq-h3" style="margin:10px 0 0">Bishop Arts &amp; Uptown</h3>
        <ul class="hq-list">
          <li>The client scans the QR code to start a parking session in the garage.</li>
          <li>Then they scan the QR code at the front desk for a two-hour validation.</li>
        </ul>
        <p class="hq-note" style="margin-top:14px">Lower Greenville: confirm the current
          arrangement before telling a client anything.
          <span class="hq-tk">Needs confirming</span></p>
      </div>

      <div class="hq-card">
        <div class="hq-eyebrow">Retail</div>
        <h3 class="hq-h3" style="margin:10px 0 0">Everything is paid for before it leaves</h3>
        <ul class="hq-list">
          <li>Clients must pay for all purchases before leaving the studio.</li>
          <li>Card on file or tap. <strong>We do not accept cash.</strong></li>
          <li>Complete the sale in Arketa — see <a href="#howtos">Arketa how-tos</a>.</li>
        </ul>
        <p class="hq-note" style="margin-top:14px">One more retail rule was sent as an
          unfinished line — “clients should not leave studio”. Finish it before this goes to
          the team. <span class="hq-tk">Needs content</span></p>
      </div>
    </div>
  </section>

  <!-- ══ 07 STUDIO ══════════════════════════════════════════════════ -->
  <section class="hq-sec" id="studio">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">07 — Studio maintenance</div>
      <h2 class="hq-h2">Opening, closing &amp; upkeep</h2>
      <p>The studio should look the same to the 7am client and the 7pm client. If something
        needs attention, post it — do not leave it for whoever is on next to discover.</p>
    </div>

    <div class="hq-grid hq-grid--2">
      <div class="hq-card">
        <div class="hq-eyebrow">Opening</div>
        <ul class="hq-list">
          <li>Lights and music on — <strong>always return the key to the Master Lock</strong>.</li>
          <li>Adjust the AC if needed.</li>
          <li>Self check-in ready.</li>
        </ul>
      </div>
      <div class="hq-card">
        <div class="hq-eyebrow">Closing</div>
        <ul class="hq-list">
          <li>Lights off or dimmed, music off.</li>
          <li>Lock the doors — <strong>always return the key to the Master Lock</strong>.</li>
        </ul>
      </div>
    </div>

    <h3 class="hq-h4" style="margin-top:32px">Routine maintenance</h3>
    <div class="hq-grid hq-grid--2" style="margin-top:14px">
      <div class="hq-card hq-card--plain">
        <div class="hq-eyebrow">Lobby &amp; front desk</div>
        <ul class="hq-list">
          <li>Coffee station stocked — pods, cups and lids, creamers, sugars, stirrers.</li>
          <li>Water cups out by the stations.</li>
          <li>Front desk and seating areas tidy.</li>
        </ul>
      </div>
      <div class="hq-card hq-card--plain">
        <div class="hq-eyebrow">Reformer studio</div>
        <ul class="hq-list">
          <li>Spot clean the floors.</li>
          <li>Props neatly arranged in their spots.</li>
          <li>Mats returned under the reformers if used.</li>
        </ul>
      </div>
      <div class="hq-card hq-card--plain">
        <div class="hq-eyebrow">Bathrooms</div>
        <ul class="hq-list">
          <li>Paper towel holders full.</li>
          <li>Toilet paper stocked.</li>
          <li>Sink areas and floors clean.</li>
        </ul>
      </div>
      <div class="hq-card hq-card--plain">
        <div class="hq-eyebrow">Trash</div>
        <ul class="hq-list">
          <li>Replace full trash bags.</li>
          <li>Take the trash to the dumpster.</li>
        </ul>
      </div>
    </div>

    <div class="hq-card" style="margin-top:22px" id="studio-issue">
      <div class="hq-eyebrow">Studio issues</div>
      <h3 class="hq-h3" style="margin:10px 0 0">Post anything that needs attention</h3>
      <p class="hq-note" style="margin-top:12px">This logs straight into the
        <b>STUDIO ISSUES</b> tab in the events workbook, so it is written down the moment
        you notice it rather than after your shift. Got a photo? Send it to Charley —
        it usually explains more than the words do.</p>

      <form class="hq-form" id="hq-issue-form">
        <div class="hq-field">
          <label for="hq-name">Your name</label>
          <input id="hq-name" name="reporter" type="text" required maxlength="80"
            autocomplete="name" placeholder="So we know who to ask if it needs a follow-up">
        </div>
        <div class="hq-row">
          <div class="hq-field">
            <label for="hq-loc">Studio</label>
            <select id="hq-loc" name="location" required>
              <option value="">Choose…</option>
              <option>Bishop Arts</option>
              <option>Uptown</option>
              <option>Lower Greenville</option>
            </select>
          </div>
          <div class="hq-field">
            <label for="hq-area">What it relates to</label>
            <select id="hq-area" name="area" required>
              <option value="">Choose…</option>
              <option>Lobby &amp; front desk</option>
              <option>Reformer studio</option>
              <option>Bathrooms</option>
              <option>Equipment</option>
              <option>Building &amp; access</option>
              <option>Something else</option>
            </select>
          </div>
        </div>
        <div class="hq-field">
          <label for="hq-detail">What needs attention</label>
          <textarea id="hq-detail" name="detail" required minlength="10"
            placeholder="Reformer 4 at Uptown — the footbar will not lock in the top position. Flagged the spot so it cannot be booked."></textarea>
        </div>
        <label class="hq-check"><input type="checkbox" name="urgent">
          Urgent — it affects classes today</label>
        <div class="hq-form__foot">
          <button class="btn btn--primary" type="submit">Log it</button>
          <span class="hq-say-status" id="hq-issue-status" role="status" aria-live="polite"></span>
        </div>
      </form>

      <p class="hq-note" style="margin-top:16px">Broken equipment: move the client first,
        log the reformer number the same day, and flag the spot so it cannot be booked.</p>
    </div>
  </section>

  <!-- ══ 08 ONBOARDING ══════════════════════════════════════════════ -->
  <section class="hq-sec" id="onboarding">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">08 — New here</div>
      <h2 class="hq-h2">Onboarding</h2>
      <p>Everything a new trainer needs in their first fortnight, in the order they need it.</p>
    </div>

    <div class="hq-card">
      <div class="hq-eyebrow">Welcome to OCP</div>
      <p class="hq-note" style="margin-top:10px">The short version of who we are and what
        the room is meant to feel like — the piece a new trainer reads before their first
        shift. <span class="hq-tk">Needs content</span></p>
    </div>

    <div class="hq-card" style="margin-top:14px">
      <div class="hq-eyebrow">Onboarding steps</div>
      <h3 class="hq-h3" style="margin:10px 0 0">Work down this list</h3>
      <p class="hq-note" style="margin-top:10px">The actual sequence — paperwork, Arketa
        account, shadow classes, first solo class, the rest.
        <span class="hq-tk">Needs content</span></p>
      <ol class="hq-steps">
        <li>Get your Arketa trainer account from Charley, and sign in before your first shift.</li>
        <li>Read the <a href="https://docs.google.com/document/d/1qxPZ9cg-ST7CLNCK0TYsXTntPhKJD_P5Ir9E-gJal04/edit" target="_blank" rel="noopener">handbook</a> end to end.</li>
        <li>Register for parking at the studios you will teach at — see below.</li>
        <li>Join Slack and turn on notifications for <b>#general</b> — that is where the team talks.</li>
        <li>Remaining steps <span class="hq-tk">Needs content</span></li>
      </ol>
    </div>

    <div class="hq-grid hq-grid--2" style="margin-top:14px">
      <div class="hq-card hq-card--plain">
        <div class="hq-eyebrow">Studio parking registration</div>
        <ul class="hq-links">
          <li><span>Bishop Arts <em><span class="hq-tk">Link needed</span></em></span></li>
          <li><span>Uptown <em><span class="hq-tk">Link needed</span></em></span></li>
          <li><span>Lower Greenville <em><span class="hq-tk">Link needed</span></em></span></li>
        </ul>
        <p class="hq-note" style="margin-top:12px">Register before your first shift at a
          studio — trainer parking is not the same as the client validation above.</p>
      </div>
      <div class="hq-card hq-card--plain">
        <div class="hq-eyebrow">Payroll</div>
        <ul class="hq-links">
          <li><span>Payroll portal <em><span class="hq-tk">Link needed</span></em></span></li>
          <li><a href="https://docs.google.com/spreadsheets/d/1ksFJqCPeZXEf2iIXxJN3kzvp5mVk6w6bEj8up9NumBw/edit" target="_blank" rel="noopener">2026 pay periods <em>Sheet</em></a></li>
        </ul>
        <p class="hq-note" style="margin-top:12px">Payroll questions go to
          <a href="mailto:Kiel@oakcliffpilates.com">Kiel@oakcliffpilates.com</a>. Never comp
          or refund a client on the spot.</p>
      </div>
    </div>
  </section>

  <!-- ══ 09 RESOURCES ═══════════════════════════════════════════════ -->
  <section class="hq-sec" id="resources">
    <div class="hq-sec__head">
      <div class="hq-eyebrow">09 — Staff resources</div>
      <h2 class="hq-h2">Resources</h2>
      <p>The documents, the how-tos and the bonus scheme. If you find yourself asking the
        desk the same question twice, it probably belongs here.</p>
    </div>

    <div class="hq-card hq-card--plain">
      <div class="hq-eyebrow">Documents</div>
      <ul class="hq-links">
        <li><a href="https://docs.google.com/document/d/1qxPZ9cg-ST7CLNCK0TYsXTntPhKJD_P5Ir9E-gJal04/edit" target="_blank" rel="noopener">Employee handbook <em>Google Doc</em></a></li>
        <li><a href="https://docs.google.com/spreadsheets/d/1ksFJqCPeZXEf2iIXxJN3kzvp5mVk6w6bEj8up9NumBw/edit" target="_blank" rel="noopener">2026 pay periods <em>Sheet</em></a></li>
        <li><a href="https://drive.google.com/drive/folders/18xeRNgO77thIr7_os57l-3i4svBLJCly" target="_blank" rel="noopener">Logos <em>Drive</em></a></li>
        <li><a href="https://drive.google.com/drive/folders/14sPj70owIHW_rCowBz7JW_9gkXLzjxwD" target="_blank" rel="noopener">Flyers <em>Drive</em></a></li>
        <li><a href="https://drive.google.com/drive/folders/1hLoFMdl-OX-zKL4ZuIOMQcMY1og9DhmL" target="_blank" rel="noopener">Photos <em>Drive</em></a></li>
        <li><a href="https://drive.google.com/drive/folders/1EPUOcVk1CNBOF8X6C-qFH_eBE7wMQ6fl" target="_blank" rel="noopener">Videos <em>Drive</em></a></li>
      </ul>
    </div>

    <div class="hq-card hq-card--plain" style="margin-top:14px">
      <div class="hq-eyebrow">Staff benefits</div>
      <p class="hq-note" style="margin-top:10px">The memberships and discounts staff get,
        and how to claim them. <span class="hq-tk">Needs content</span></p>
    </div>

    <h3 class="hq-h4" style="margin-top:36px" id="howtos">Arketa how-tos</h3>
    <p class="hq-note" style="margin:8px 0 14px">Short screen shares. Open Arketa before you
      unlock the door, not after class starts.</p>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ht-1">
        <span class="hq-acc__sign"></span>Class management
      </button>
      <div class="hq-acc__panel" id="ht-1" hidden>
        <ul class="hq-links">
          <li><span>Navigating Arketa <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>The class roster <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Navigating a client’s profile <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Checking a client in <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Adding a client to a class <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Cancelling a reservation <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Adding a client off the waitlist <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Requesting and claiming a sub <em><span class="hq-tk">Video needed</span></em></span></li>
        </ul>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ht-2">
        <span class="hq-acc__sign"></span>Retail
      </button>
      <div class="hq-acc__panel" id="ht-2" hidden>
        <ul class="hq-links">
          <li><span>Completing a purchase <em><span class="hq-tk">Video needed</span></em></span></li>
        </ul>
      </div>
    </div>

    <div class="hq-acc">
      <button class="hq-acc__btn" type="button" aria-expanded="false" aria-controls="ht-3">
        <span class="hq-acc__sign"></span>Private sessions
      </button>
      <div class="hq-acc__panel" id="ht-3" hidden>
        <ul class="hq-links">
          <li><span>Setting up a private through OCP <em><span class="hq-tk">Video needed</span></em></span></li>
          <li><span>Setting up a private through Private Space Rental <em><span class="hq-tk">Video needed</span></em></span></li>
        </ul>
      </div>
    </div>

    <div class="hq-card" style="margin-top:32px">
      <div class="hq-eyebrow">Bonus programme — trainers</div>
      <h3 class="hq-h3" style="margin:10px 0 0">Quarterly bonus</h3>
      <p class="hq-note" style="margin-top:10px">
        <strong>Proposed — not yet in effect.</strong> Full detail in the
        <a href="https://docs.google.com/document/d/11G8V1PHvrHYahp56XRzoOIXEWt7HfHQsrD91YZByuH0/edit" target="_blank" rel="noopener">proposal document</a>.
      </p>

      <div class="hq-grid hq-grid--2" style="margin-top:18px">
        <div>
          <h4 class="hq-h4">The opportunity</h4>
          <ul class="hq-list">
            <li><strong>8 or fewer weekly classes</strong> (averaged per quarter) — up to
              <strong>$500 a year</strong>, or $125 a quarter.</li>
            <li><strong>9 or more weekly classes</strong> (averaged per quarter) — up to
              <strong>$1,000 a year</strong>, or $250 a quarter.</li>
          </ul>
        </div>
        <div>
          <h4 class="hq-h4">Must meet all three</h4>
          <ul class="hq-list">
            <li><strong>Schedule commitment:</strong> teach at least 80% of your regularly
              scheduled classes for the quarter.</li>
            <li><strong>Team support:</strong> sub at least 2 classes in the quarter.</li>
            <li><strong>Reliability:</strong> zero documented no-shows or late arrivals.</li>
          </ul>
        </div>
      </div>

      <h4 class="hq-h4" style="margin-top:22px">Plus at least two of these</h4>
      <ul class="hq-list">
        <li><strong>Staff engagement:</strong> attend an all-staff event held during the
          quarter, if there is one.</li>
        <li><strong>Client experience:</strong> receive a 5-star review or other validated
          positive client feedback attributable to you.</li>
        <li><strong>Professional development:</strong> attend at least one OCP
          professional-development opportunity in the quarter.</li>
        <li><strong>Class performance:</strong> maintain at least 55% average utilisation
          across your eligible regularly scheduled classes.</li>
      </ul>
    </div>

    <div class="hq-card hq-card--plain" style="margin-top:14px">
      <div class="hq-eyebrow">Front desk</div>
      <h3 class="hq-h3" style="margin:10px 0 0">To-do list &amp; desk resources</h3>
      <p class="hq-note" style="margin-top:10px">The opening, mid-day and closing desk
        checklist, and whatever the desk needs to hand.
        <span class="hq-tk">Needs content</span></p>
    </div>

    <div class="hq-card" style="margin-top:14px">
      <div class="hq-eyebrow">Who to ask</div>
      <div class="hq-grid hq-grid--3" style="margin-top:14px">
        <div>
          <h4 class="hq-h4">Schedule &amp; subs</h4>
          <p class="hq-note" style="margin-top:6px"><a href="mailto:Charley@oakcliffpilates.com">Charley@oakcliffpilates.com</a></p>
        </div>
        <div>
          <h4 class="hq-h4">Events &amp; marketing</h4>
          <p class="hq-note" style="margin-top:6px"><a href="mailto:Isabel@oakcliffpilates.com">Isabel@oakcliffpilates.com</a></p>
        </div>
        <div>
          <h4 class="hq-h4">Payroll</h4>
          <p class="hq-note" style="margin-top:6px"><a href="mailto:Kiel@oakcliffpilates.com">Kiel@oakcliffpilates.com</a></p>
        </div>
      </div>
      <p class="hq-note" style="margin-top:18px">Need a sub or running late? Text Amanda as
        early as you can — not the group chat.</p>
    </div>
  </section>

  </main>
</div>

<script src="/js/portal.js?v=0279ef74aa" defer></script>
</body>
</html>
`;

function render() {
  return PAGE;
}

module.exports = { render, version: "0279ef74aa" };
